openapi: 3.0.0
info:
  title: Game Results API
  description: Документация для API результатов игры
  version: 1.0.0
servers:
  - url: http://localhost:8000/api
    description: Локальный сервер разработки
paths:
  /results:
    post:
      summary: Создание нового результата
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                member_id:
                  type: integer
                milliseconds:
                  type: integer
      responses:
        '201':
          description: Результат успешно создан
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Result'
        '400':
          description: Неверные входные данные

  /results/top:
    get:
      summary: Получить топ 10 результатов
      parameters:
        - name: email
          in: query
          description: Email пользователя для фильтрации топ результатов
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      top:
                        type: array
                        items:
                          $ref: '#/components/schemas/Result'
                      self:
                        $ref: '#/components/schemas/UserResult'

components:
  schemas:
    Result:
      type: object
      properties:
        id:
          type: integer
          format: int64
        member_id:
          type: integer
          format: int64
        milliseconds:
          type: integer
          format: int64
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    UserResult:
      type: object
      properties:
        id:
          type: integer
          format: int64
        email:
          type: string
        milliseconds:
          type: integer
          format: int64
